name: Build Docker Image

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-builder:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Docker login
              run: echo ${{ secrets.CI_REGISTRY_PASSWORD }} | docker login -u ${{ secrets.CI_REGISTRY_USER }} --password-stdin ${{ secrets.CI_REGISTRY }}

            - name: Build and push base image for builder
              run: |
                  docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ${{ secrets.CI_REGISTRY_IMAGE }}/test:latest --target builder -t ${{ secrets.CI_REGISTRY_IMAGE }}/test:latest .
                  docker push ${{ secrets.CI_REGISTRY_IMAGE }}/test:latest
